export const privacyPolicy = {
  "/legal/privacy-policy": {
    "version": 1,
    "title": "Privacy Policy - Groupe ANJ",
    "description": "Groupe ANJ est un cabinet de comptabilité et de services-conseils offrant la tenue de livres, la fiscalité, la préparation des états financiers et un accompagnement clair pour soutenir des décisions éclairées et la conformité.",
    "keywords": "",
    "h1": [
      "Privacy Policy"
    ],
    "h2": [],
    "h3": [
      "Introduction",
      "Information We Collect",
      "How We Use Your Information",
      "Data Sharing and Disclosure",
      "Data Security",
      "Your Rights and Choices",
      "Children's Privacy",
      "Changes to This Policy",
      "Contact Us"
    ],
    "h4": [],
    "h5": [],
    "h6": [],
    "p": [
      "Home",
      "About",
      "Services",
      "Contact Us",
      "Last updated : Nov 16, 2023",
      "Welcome to Groupe ANJ inc. ! We are committed to protecting the privacy and security of your personal information. This Privacy Policy outlines how we collect, use, and safeguard your data when you use our website www.groupeanj.ca or our services.",
      "Personal Information: When you register an account or use our services, we may collect personal information such as your name, email address, phone number, and billing information.",
      "Usage Data: We gather information about how you interact with our website or services, including IP address, browser type, pages visited, and device information.",
      "Cookies: We use cookies and similar tracking technologies to enhance your experience and gather data about your preferences and browsing behavior.",
      "We use the information we collect for the following purposes:",
      "Providing and improving our services",
      "Personalizing your experience",
      "Communicating with you about updates, promotions, and offers",
      "Analyzing usage trends and optimizing our website",
      "We may share your information with third parties in the following circumstances:",
      "With your consent or at your direction",
      "To comply with legal obligations or respond to legal requests",
      "To protect our rights, property, or safety, or the rights, property, or safety of others",
      "In connection with a merger, acquisition, or sale of assets",
      "We implement security measures to protect your personal information from unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet or electronic storage is 100% secure, and we cannot guarantee absolute security.",
      "You have the right to:",
      "Access and update your personal information",
      "Opt-out of receiving promotional communications",
      "Request the deletion of your account and data",
      "Our services are not intended for children under the age of 13. We do not knowingly collect or solicit personal information from minors. If you believe that a child has provided us with personal information, please contact us immediately.",
      "We may update this Privacy Policy periodically. We will notify you of any changes by posting the new policy on this page.",
      "If you have any questions or concerns about our Privacy Policy, please contact us at info@groupeanj.ca.",
      "Empowering smarter financial decisions through strategy, insight, and innovation.",
      "About Us",
      "Contact",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "Phone",
      "(514) 231-7151",
      "Email Address",
      "info@groupeanj.ca",
      "Terms of Service",
      "Privacy Policy",
      "© 2025 Groupe ANJ Inc. All Rights Reserved.",
      "Create a free website with Framer, the website builder loved by startups, designers and agencies."
    ],
    "codeblock": [],
    "url": "/legal/privacy-policy"
  },
  "/legal/terms-of-service": {
    "version": 1,
    "title": "Terms of Service - Groupe ANJ",
    "description": "Groupe ANJ est un cabinet de comptabilité et de services-conseils offrant la tenue de livres, la fiscalité, la préparation des états financiers et un accompagnement clair pour soutenir des décisions éclairées et la conformité.",
    "keywords": "",
    "h1": [
      "Terms of Service"
    ],
    "h2": [],
    "h3": [
      "Introduction",
      "User Responsibilities",
      "Intellectual Property",
      "Privacy",
      "Payment and Billing",
      "Disclaimer of Warranties",
      "Limitation of Liability",
      "Indemnification",
      "Governing Law",
      "Changes to Terms",
      "Contact Us"
    ],
    "h4": [],
    "h5": [],
    "h6": [],
    "p": [
      "Home",
      "About",
      "Services",
      "Contact Us",
      "Last updated : Dec 18, 2023",
      "Welcome to Groupe ANJ inc. ! These Terms of Service govern your use of our website www.groupeanj.ca and services. By accessing or using our platform, you agree to comply with these terms and conditions.",
      "Account Creation: If you create an account, you are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.",
      "Prohibited Activities: You agree not to engage in any illegal, unauthorized, or abusive activities on our platform. This includes but is not limited to spamming, hacking, and violating intellectual property rights.",
      "Content Guidelines: You are responsible for the content you upload, post, or share on our platform. Content must not infringe upon the rights of others or contain offensive, defamatory, or harmful material.",
      "Our platform and its content, including but not limited to text, graphics, logos, and software, are protected by intellectual property laws. You may not use, reproduce, or distribute our content without our express permission.",
      "Your privacy is important to us. Please review our Privacy Policy to understand how we collect, use, and protect your personal information.",
      "If our services require payment, you agree to pay all applicable fees and charges. Payments are processed securely, and we do not store your payment information.",
      "Our platform is provided \"as is\" without warranties of any kind, express or implied. We do not guarantee the accuracy, reliability, or suitability of our services for your specific needs.",
      "In no event shall Groupe ANJ inc. be liable for any damages arising from your use of our platform, including but not limited to direct, indirect, incidental, or consequential damages.",
      "You agree to indemnify and hold harmless Groupe ANJ inc., its affiliates, and employees from any claims, damages, or liabilities arising from your use of our platform or violation of these terms.",
      "These Terms of Service are governed by the laws of Canada/Québec. Any disputes arising from these terms shall be resolved through arbitration in Montréal.",
      "We reserve the right to update or modify these terms at any time. We will notify you of any changes by posting the revised terms on our platform.",
      "If you have any questions or concerns about our Terms of Service, please contact us at info@groupeanj.ca.",
      "Empowering smarter financial decisions through strategy, insight, and innovation.",
      "About Us",
      "Contact",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "Phone",
      "(514) 231-7151",
      "Email Address",
      "info@groupeanj.ca",
      "Terms of Service",
      "Privacy Policy",
      "© 2025 Groupe ANJ Inc. All Rights Reserved.",
      "Create a free website with Framer, the website builder loved by startups, designers and agencies."
    ],
    "codeblock": [],
    "url": "/legal/terms-of-service"
  },
  "/service/financial-reports-analysis": {
    "version": 1,
    "title": "Groupe ANJ | Services comptables, fiscaux et conseils",
    "description": "Groupe ANJ est un cabinet de comptabilité et de services-conseils offrant la tenue de livres, la fiscalité, la préparation des états financiers et un accompagnement clair pour soutenir des décisions éclairées et la conformité.",
    "keywords": "",
    "h1": [
      "Financial Reports & Analysis"
    ],
    "h2": [
      "Clear financial reports and analysis for informed oversight",
      "Financial Reports & Analysis — What’s Included",
      "A structured approach to financial reporting and analysis",
      "Let’s build clarity, confidence, and growth together",
      "Other Services"
    ],
    "h3": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6"
    ],
    "h4": [],
    "h5": [],
    "h6": [
      "Periodic Financial Reports",
      "Income & Expense Analysis",
      "Comparative Reporting",
      "Variance Identification",
      "Supporting Schedules",
      "Summary & Interpretation",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management"
    ],
    "p": [
      "Home",
      "About",
      "Services",
      "Contact Us",
      "Interpretability",
      "Consistency",
      "Usefulness",
      "What we do",
      "We prepare structured financial reports and practical analysis to help clients understand their financial position, monitor performance, and support informed planning and decision-making.",
      "Services Offered",
      "Preparation of regular financial reports based on bookkeeping records and financial statements.",
      "Review and analysis of revenues and expenses to highlight trends and variations over time.",
      "Comparison of financial results across periods to support performance monitoring and consistency.",
      "Identification of notable changes or variances to support follow-up and review.",
      "Preparation of supporting schedules to provide additional detail and context to reported figures.",
      "Clear summaries to help clients understand key results and how the information can be used.",
      "How we work",
      "We follow a clear and consistent process to ensure financial reports are reliable, understandable, and useful.",
      "Report Preparation",
      "Financial reports and schedules are prepared using structured formats for clarity and comparability.",
      "Data Review & Validation",
      "We begin by reviewing bookkeeping and financial data to ensure completeness and consistency.",
      "Analysis & Review",
      "We analyze results to identify key observations, trends, and notable variations.",
      "Delivery & Discussion",
      "We deliver finalized reports and provide explanations to support understanding and next steps.",
      "Get in Touch",
      "Contact us to discuss your bookkeeping and accounting needs.",
      "First name",
      "Last name",
      "Email",
      "Phone",
      "Service",
      "Message",
      "Submit",
      "More Details",
      "Empowering smarter financial decisions through strategy, insight, and innovation.",
      "About Us",
      "Contact",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "(514) 231-7151",
      "Email Address",
      "info@groupeanj.ca",
      "Terms of Service",
      "Privacy Policy",
      "© 2025 Groupe ANJ Inc. All Rights Reserved.",
      "Create a free website with Framer, the website builder loved by startups, designers and agencies."
    ],
    "codeblock": [],
    "url": "/service/financial-reports-analysis"
  },
  "/service/payroll-management": {
    "version": 1,
    "title": "Groupe ANJ | Services comptables, fiscaux et conseils",
    "description": "Groupe ANJ est un cabinet de comptabilité et de services-conseils offrant la tenue de livres, la fiscalité, la préparation des états financiers et un accompagnement clair pour soutenir des décisions éclairées et la conformité.",
    "keywords": "",
    "h1": [
      "Payroll Management"
    ],
    "h2": [
      "Reliable payroll management for accurate and compliant processing",
      "Payroll Management — What’s Included",
      "A structured approach to payroll management",
      "Let’s build clarity, confidence, and growth together",
      "Other Services"
    ],
    "h3": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6"
    ],
    "h4": [],
    "h5": [],
    "h6": [
      "Payroll Processing",
      "Statutory Deductions & Remittances",
      "Payroll Records Maintenance",
      "Year-End Payroll Reporting",
      "Employee & Employer Contributions",
      "Payroll Compliance Support",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Financial Reports & Analysis"
    ],
    "p": [
      "Home",
      "About",
      "Services",
      "Contact Us",
      "Accuracy",
      "Compliance",
      "Reliability",
      "What we do",
      "We provide payroll management services to ensure employee compensation is calculated accurately, remittances are submitted on time, and payroll records remain compliant with applicable regulations.",
      "Services Offered",
      "Accurate calculation and processing of employee wages, deductions, and net pay.",
      "Calculation and submission of required payroll remittances to the appropriate authorities.",
      "Ongoing maintenance of organized and accurate payroll records to support compliance and reporting.",
      "Preparation of year-end payroll forms and summaries in accordance with reporting requirements.",
      "Management of required employer and employee contributions as part of payroll processing.",
      "Support to ensure payroll practices align with applicable regulations and reporting obligations.",
      "How we work",
      "We follow a clear and methodical process to ensure payroll is processed accurately, consistently, and on time.",
      "Payroll Calculation & Processing",
      "We calculate payroll amounts and apply required deductions for each pay period.",
      "Information Collection & Setup",
      "We begin by collecting employee information and setting up payroll parameters based on your business needs.",
      "Remittances & Reporting",
      "We submit payroll remittances and prepare required reports in accordance with deadlines.",
      "Review & Ongoing Support",
      "We review payroll records regularly and remain available to address questions or adjustments.",
      "Get in Touch",
      "Contact us to discuss your bookkeeping and accounting needs.",
      "First name",
      "Last name",
      "Email",
      "Phone",
      "Service",
      "Message",
      "Submit",
      "More Details",
      "Empowering smarter financial decisions through strategy, insight, and innovation.",
      "About Us",
      "Contact",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "(514) 231-7151",
      "Email Address",
      "info@groupeanj.ca",
      "Terms of Service",
      "Privacy Policy",
      "© 2025 Groupe ANJ Inc. All Rights Reserved.",
      "Create a free website with Framer, the website builder loved by startups, designers and agencies."
    ],
    "codeblock": [],
    "url": "/service/payroll-management"
  },
  "/contact": {
    "version": 1,
    "title": "Groupe ANJ | Services comptables, fiscaux et conseils",
    "description": "Groupe ANJ est un cabinet de comptabilité et de services-conseils offrant la tenue de livres, la fiscalité, la préparation des états financiers et un accompagnement clair pour soutenir des décisions éclairées et la conformité.",
    "keywords": "",
    "h1": [
      "Get in Touch"
    ],
    "h2": [],
    "h3": [],
    "h4": [],
    "h5": [
      "Send us a message"
    ],
    "h6": [],
    "p": [
      "Home",
      "About",
      "Services",
      "Contact Us",
      "Contact us",
      "At Groupe ANJ, we believe effective accounting support starts with clear communication. Whether you need assistance with bookkeeping, tax compliance, or financial reporting, we’re here to help and ready to connect.",
      "Email Address",
      "info@groupeanj.ca",
      "Phone",
      "+1 (514) 231-7151",
      "Business hours",
      "Monday – Friday: 9:00 AM – 6:00 PM",
      "Saturday – Sunday: Closed",
      "First name",
      "Last name",
      "Email",
      "Message",
      "Submit",
      "Empowering smarter financial decisions through strategy, insight, and innovation.",
      "About Us",
      "Contact",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "(514) 231-7151",
      "Terms of Service",
      "Privacy Policy",
      "© 2025 Groupe ANJ Inc. All Rights Reserved.",
      "Create a free website with Framer, the website builder loved by startups, designers and agencies."
    ],
    "codeblock": [],
    "url": "/contact"
  },
  "/service/tax-compliance-filings": {
    "version": 1,
    "title": "Groupe ANJ | Services comptables, fiscaux et conseils",
    "description": "Groupe ANJ est un cabinet de comptabilité et de services-conseils offrant la tenue de livres, la fiscalité, la préparation des états financiers et un accompagnement clair pour soutenir des décisions éclairées et la conformité.",
    "keywords": "",
    "h1": [
      "Tax Compliance & Filings"
    ],
    "h2": [
      "Tax Compliance & Filings — What’s Included",
      "Comprehensive tax compliance services for accuracy and peace of mind",
      "A structured approach to tax compliance and filings",
      "Let’s build clarity, confidence, and growth together",
      "Other Services"
    ],
    "h3": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6"
    ],
    "h4": [],
    "h5": [],
    "h6": [
      "Tax Return Preparation",
      "Tax Filings & Submissions",
      "Compliance Review",
      "Support for Tax Authorities’ Requests",
      "Coordination With Financial Records",
      "Clear Tax Reporting",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Payroll Management",
      "Financial Reports & Analysis"
    ],
    "p": [
      "Home",
      "About",
      "Services",
      "Contact Us",
      "Accuracy",
      "Compliance",
      "Clarity",
      "What we do",
      "Services Offered",
      "Preparation of corporate and personal tax returns based on complete and accurate financial information.",
      "Timely filing of tax returns and required forms with the appropriate tax authorities.",
      "Review of tax information to ensure completeness, consistency, and compliance with applicable regulations.",
      "Assistance with notices, requests for information, and follow-ups from tax authorities.",
      "Alignment of tax filings with bookkeeping records and financial statements to ensure consistency.",
      "Clear summaries and explanations to help clients understand their tax position and obligations.",
      "How we work",
      "We follow a clear, methodical process to ensure tax filings are accurate, complete, and submitted in accordance with applicable tax laws and deadlines.",
      "Preparation & Verification",
      "Tax returns and required forms are prepared carefully, with thorough verification to ensure accuracy and consistency with financial records.",
      "Information Collection & Review",
      "We begin by gathering and reviewing the necessary financial and tax information to understand your situation and filing requirements.",
      "Filing & Submission",
      "We file tax returns and related documents with the appropriate tax authorities, ensuring timely and compliant submissions.",
      "Follow-Up & Support",
      "We remain available to address questions, provide clarification, and assist with follow-ups or requests from tax authorities.",
      "Get in Touch",
      "Contact us to discuss your bookkeeping and accounting needs.",
      "First name",
      "Last name",
      "Email",
      "Phone",
      "Service",
      "Message",
      "Submit",
      "More Details",
      "Empowering smarter financial decisions through strategy, insight, and innovation.",
      "About Us",
      "Contact",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "(514) 231-7151",
      "Email Address",
      "info@groupeanj.ca",
      "Terms of Service",
      "Privacy Policy",
      "© 2025 Groupe ANJ Inc. All Rights Reserved.",
      "Create a free website with Framer, the website builder loved by startups, designers and agencies."
    ],
    "codeblock": [],
    "url": "/service/tax-compliance-filings"
  },
  "/service/bookkeeping": {
    "version": 1,
    "title": "Groupe ANJ | Services comptables, fiscaux et conseils",
    "description": "Groupe ANJ est un cabinet de comptabilité et de services-conseils offrant la tenue de livres, la fiscalité, la préparation des états financiers et un accompagnement clair pour soutenir des décisions éclairées et la conformité.",
    "keywords": "",
    "h1": [
      "Bookkeeping"
    ],
    "h2": [
      "Reliable bookkeeping for clear financial records",
      "Bookkeeping — What’s Included",
      "Our process for clear and reliable bookkeeping",
      "Let’s build clarity, confidence, and growth together",
      "Other Services"
    ],
    "h3": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6"
    ],
    "h4": [],
    "h5": [],
    "h6": [
      "Transaction Recording",
      "Account Reconciliation",
      "Expense & Income Tracking",
      "Accounts Payable & Receivable",
      "Financial Record Maintenance",
      "Periodic Reporting Support",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis"
    ],
    "p": [
      "Home",
      "About",
      "Services",
      "Contact Us",
      "Strategy",
      "Security",
      "Growth",
      "What we do",
      "We maintain accurate and organized financial records by recording transactions, reconciling accounts, and ensuring your books are kept up to date and ready for reporting and compliance.",
      "Services Offered",
      "Accurate recording of day-to-day financial transactions to ensure your books reflect your business activity correctly.",
      "Regular reconciliation of bank and credit card accounts to ensure consistency, accuracy, and completeness of records.",
      "Clear tracking and categorization of expenses and revenues to support visibility, control, and reporting.",
      "Monitoring payables and receivables to support cash flow visibility and timely follow-up.",
      "Ongoing maintenance of organized and compliant financial records to support audits, reporting, and tax filings.",
      "Preparation of structured bookkeeping reports to support financial oversight and collaboration with tax or advisory professionals.",
      "How we work",
      "We follow a structured and transparent approach to ensure your financial records are accurate, organized, and up to date.",
      "Initial Review & Setup",
      "We begin by understanding your business, reviewing existing records, and setting up or aligning your bookkeeping structure.",
      "Transaction Recording",
      "We record financial transactions accurately and consistently, ensuring proper categorization and documentation.",
      "Reconciliation & Verification",
      "We reconcile accounts regularly to verify accuracy and identify discrepancies early.",
      "Ongoing Maintenance & Reporting",
      "We maintain organized records and prepare periodic bookkeeping reports to support oversight, tax preparation, and financial reporting.",
      "Get in Touch",
      "Contact us to discuss your bookkeeping and accounting needs.",
      "First name",
      "Last name",
      "Email",
      "Phone",
      "Service",
      "Message",
      "Submit",
      "More Details",
      "Empowering smarter financial decisions through strategy, insight, and innovation.",
      "About Us",
      "Contact",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "(514) 231-7151",
      "Email Address",
      "info@groupeanj.ca",
      "Terms of Service",
      "Privacy Policy",
      "© 2025 Groupe ANJ Inc. All Rights Reserved.",
      "Create a free website with Framer, the website builder loved by startups, designers and agencies."
    ],
    "codeblock": [],
    "url": "/service/bookkeeping"
  },
  "/service/financial-statements-preparation": {
    "version": 1,
    "title": "Groupe ANJ | Services comptables, fiscaux et conseils",
    "description": "Groupe ANJ est un cabinet de comptabilité et de services-conseils offrant la tenue de livres, la fiscalité, la préparation des états financiers et un accompagnement clair pour soutenir des décisions éclairées et la conformité.",
    "keywords": "",
    "h1": [
      "Financial Statements Preparation"
    ],
    "h2": [
      "Accurate financial statements prepared with clarity and compliance",
      "Financial Statements Preparation — What’s Included",
      "A structured approach to financial statement preparation",
      "Let’s build clarity, confidence, and growth together",
      "Other Services"
    ],
    "h3": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6"
    ],
    "h4": [],
    "h5": [],
    "h6": [
      "Trial Balance Review",
      "Adjusting Entries",
      "Statement of Financial Position",
      "Statement of Results",
      "Supporting Schedules",
      "Compliance Alignment",
      "Bookkeeping",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis"
    ],
    "p": [
      "Home",
      "About",
      "Services",
      "Contact Us",
      "Consistency",
      "Reliability",
      "Transparency",
      "What we do",
      "We prepare financial statements in accordance with applicable accounting standards, providing reliable and structured financial information for tax filings, internal oversight, and external use. Our focus is on accuracy, consistency, and clear presentation.",
      "Services Offered",
      "Review and validation of bookkeeping records to ensure completeness and consistency before statement preparation.",
      "Preparation of necessary accruals, amortization, and adjustments to reflect accurate financial results.",
      "Preparation of balance sheets that clearly present assets, liabilities, and equity.",
      "Preparation of income statements showing revenues, expenses, and net results for the period.",
      "Preparation of supporting schedules and notes to provide clarity and context to the financial statements.",
      "Ensuring financial statements align with bookkeeping records and tax reporting requirements.",
      "How we work",
      "We follow a clear and methodical process to ensure financial statements are accurate, compliant, and easy to understand.",
      "Preparation & Adjustments",
      "We prepare financial statements and apply required adjustments in accordance with accounting standards.",
      "Review & Information Gathering",
      "We begin by reviewing your bookkeeping records and gathering the necessary financial information.",
      "Verification & Consistency Checks",
      "We verify totals, classifications, and consistency across all financial statements and schedules.",
      "Delivery & Explanation",
      "We deliver finalized financial statements and provide clear explanations to support understanding and next steps.",
      "Get in Touch",
      "Contact us to discuss your bookkeeping and accounting needs.",
      "First name",
      "Last name",
      "Email",
      "Phone",
      "Service",
      "Message",
      "Submit",
      "More Details",
      "Empowering smarter financial decisions through strategy, insight, and innovation.",
      "About Us",
      "Contact",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "(514) 231-7151",
      "Email Address",
      "info@groupeanj.ca",
      "Terms of Service",
      "Privacy Policy",
      "© 2025 Groupe ANJ Inc. All Rights Reserved.",
      "Create a free website with Framer, the website builder loved by startups, designers and agencies."
    ],
    "codeblock": [],
    "url": "/service/financial-statements-preparation"
  },
  "/service": {
    "version": 1,
    "title": "Groupe ANJ | Services comptables, fiscaux et conseils",
    "description": "Groupe ANJ est un cabinet de comptabilité et de services-conseils offrant la tenue de livres, la fiscalité, la préparation des états financiers et un accompagnement clair pour soutenir des décisions éclairées et la conformité.",
    "keywords": "",
    "h1": [
      "Accounting, tax, and advisory services built around your Business"
    ],
    "h2": [
      "Frequently Asked Questions",
      "Partner with experts who understand your financial vision"
    ],
    "h3": [],
    "h4": [],
    "h5": [],
    "h6": [
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "What types of clients do you work with?",
      "How do you structure your consulting engagements?",
      "Are your services customizable?",
      "Do you offer confidential consulting?",
      "How can I get started?"
    ],
    "p": [
      "Home",
      "About",
      "Services",
      "Contact Us",
      "Our Services",
      "More Details",
      "FAQ",
      "We’ve compiled answers to some of the most common questions about our consulting services, process, and partnerships.",
      "We partner with individuals, startups, and established organizations across various industries — from finance and technology to sustainability and healthcare. Our approach adapts to the scale and goals of each client.",
      "Get in Touch",
      "Let’s discuss how our consulting solutions can help you plan smarter, grow stronger, and achieve lasting success.",
      "Empowering smarter financial decisions through strategy, insight, and innovation.",
      "About Us",
      "Contact",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "Phone",
      "(514) 231-7151",
      "Email Address",
      "info@groupeanj.ca",
      "Terms of Service",
      "Privacy Policy",
      "© 2025 Groupe ANJ Inc. All Rights Reserved.",
      "Create a free website with Framer, the website builder loved by startups, designers and agencies."
    ],
    "codeblock": [],
    "url": "/service"
  },
  "/about": {
    "version": 1,
    "title": "Groupe ANJ | Services comptables, fiscaux et conseils",
    "description": "Groupe ANJ est un cabinet de comptabilité et de services-conseils offrant la tenue de livres, la fiscalité, la préparation des états financiers et un accompagnement clair pour soutenir des décisions éclairées et la conformité.",
    "keywords": "",
    "h1": [
      "Empowering businesses with financial clarity and lasting growth"
    ],
    "h2": [
      "The principles that define how we work",
      "Strategic insight. Trusted partnership.",
      "Partner with experts who understand your financial vision"
    ],
    "h3": [],
    "h4": [],
    "h5": [
      "Integrity",
      "Service Excellence",
      "Confidentiality"
    ],
    "h6": [],
    "p": [
      "Home",
      "About",
      "Services",
      "Contact Us",
      "About Us",
      "Groupe ANJ is an accounting and advisory firm committed to precision, integrity, and innovation.We support businesses with financial reporting, taxation, and compliance services, helping them make informed decisions and build sustainable long-term success.",
      "Core Values",
      "Our values underpin every client relationship and strategic decision, ensuring clarity, trust, and meaningful, measurable impact.",
      "We believe trust is earned through transparency, accountability, and consistency. Every decision we make is guided by honesty and a deep respect for our clients’ goals and interests.",
      "We deliver high-quality accounting services with professionalism, responsiveness, and care. Every engagement is handled with attention to detail and a commitment.",
      "We safeguard our clients’ financial information with the highest level of discretion and care. All data is handled responsibly, securely, and in accordance with professional and legal requirements.",
      "Why Choose Us",
      "Choosing Groupe ANJ means working with a dedicated accounting firm focused on clarity, accuracy, and personalized service. We take the time to understand your business, provide practical financial guidance, and support decisions that create long-term value.",
      "Personalized Attention",
      "As a growing firm, we offer hands-on support and direct communication. Every client receives tailored guidance aligned with their specific needs and goals.",
      "Strong Technical Foundation",
      "Our work is grounded in solid accounting principles, current standards, and rigorous attention to detail—ensuring accuracy, compliance, and reliability from day one.",
      "Clear & Transparent Communication",
      "We believe financial information should be easy to understand. We communicate openly and clearly so you always know where you stand and why decisions matter.",
      "Practical, Growth-Focused Support",
      "Our focus is on delivering useful, actionable insights that help strengthen financial organization, improve efficiency, and support sustainable growth.",
      "Get in Touch",
      "Let’s discuss how our consulting solutions can help you plan smarter, grow stronger, and achieve lasting success.",
      "Our Services",
      "Empowering smarter financial decisions through strategy, insight, and innovation.",
      "Contact",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "Phone",
      "(514) 231-7151",
      "Email Address",
      "info@groupeanj.ca",
      "Terms of Service",
      "Privacy Policy",
      "© 2025 Groupe ANJ Inc. All Rights Reserved.",
      "Create a free website with Framer, the website builder loved by startups, designers and agencies."
    ],
    "codeblock": [],
    "url": "/about"
  },
  "/": {
    "version": 1,
    "title": "Groupe ANJ | Services comptables, fiscaux et conseils",
    "description": "Groupe ANJ est un cabinet de comptabilité et de services-conseils offrant la tenue de livres, la fiscalité, la préparation des états financiers et un accompagnement clair pour soutenir des décisions éclairées et la conformité.",
    "keywords": "",
    "h1": [
      "Professional Accounting Services Built on Confidentiality and Integrity"
    ],
    "h2": [
      "Comprehensive consulting for every financial need",
      "Why clients choose us",
      "Sustainable Growth",
      "Frequently Asked Questions",
      "Partner with experts who understand your financial vision"
    ],
    "h3": [
      "We provide practical accounting and advisory support, helping businesses and individuals navigate financial matters with clarity, accuracy, and confidence."
    ],
    "h4": [],
    "h5": [
      "Tailored Strategies",
      "Precision You Can Trust",
      "Trusted Partnership"
    ],
    "h6": [
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "What types of clients do you work with?",
      "How do you structure your consulting engagements?",
      "Are your services customizable?",
      "Do you offer confidential consulting?",
      "How can I get started?"
    ],
    "p": [
      "Home",
      "About",
      "Services",
      "Contact Us",
      "We provide bookkeeping, tax compliance, and financial reporting services to help businesses operate with clarity and confidence.",
      "Our Services",
      "From financial organization to ongoing compliance and planning, our services help businesses and individuals gain clarity, maintain control, and support long-term stability.",
      "More Details",
      "About Us",
      "Built on strong accounting foundations, Groupe ANJ provides practical financial and advisory services focused on accuracy, clarity, and reliability. Our approach emphasizes structured financial information, thoughtful guidance, and support tailored to each client’s needs.",
      "At our core, we value precision, transparency, and clear communication—ensuring every engagement is grounded in trust and professional integrity.",
      "Service Excellence",
      "Reliable, responsive accounting services delivered with care and attention to detail.",
      "Integrity",
      "Transparent and ethical guidance at every step.",
      "Confidentiality",
      "We safeguard client information with strict confidentiality and care.",
      "More About Our Story",
      "Our Values",
      "We go beyond traditional consulting by combining financial expertise with strategic insight.",
      "Every client receives customized financial and business solutions aligned with their unique goals.",
      "We focus not only on immediate results but also on long-term value and resilience.",
      "55%",
      "2022",
      "72%",
      "2023",
      "87%",
      "2024",
      "Accurate, compliant, and well-structured accounting services delivered with care and attention to detail.",
      "Our client-first approach is built on transparency, integrity, and lasting collaboration.",
      "FAQ",
      "We’ve compiled answers to some of the most common questions about our consulting services, process, and partnerships.",
      "We partner with individuals, startups, and established organizations across various industries — from finance and technology to sustainability and healthcare. Our approach adapts to the scale and goals of each client.",
      "Get in Touch",
      "Let’s discuss how our consulting solutions can help you plan smarter, grow stronger, and achieve lasting success.",
      "Empowering smarter financial decisions through strategy, insight, and innovation.",
      "Contact",
      "Bookkeeping",
      "Financial Statements Preparation",
      "Tax Compliance & Filings",
      "Payroll Management",
      "Financial Reports & Analysis",
      "Phone",
      "(514) 231-7151",
      "Email Address",
      "info@groupeanj.ca",
      "Terms of Service",
      "Privacy Policy",
      "© 2025 Groupe ANJ Inc. All Rights Reserved.",
      "Create a free website with Framer, the website builder loved by startups, designers and agencies."
    ],
    "codeblock": [],
    "url": "/"
  }
};